GET https://localhost:9000/


###

POST https://localhost:9000/vendors
Content-Type: application/json 
Cache-Control: public, max-age=3600
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1ZUBjb21wYW55LmNvbSIsInN1YiI6InN1ZUBjb21wYW55LmNvbSIsImp0aSI6IjY3OTY5ZWU0Iiwicm9sZSI6WyJTb2Z0d2FyZUNlbnRlciIsIk1hbmFnZXIiXSwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6OTAwMCIsIm5iZiI6MTc4MTAzNjczOSwiZXhwIjoxNzg4OTg1NTM5LCJpYXQiOjE3ODEwMzY3NDEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.wNZO9MA1kIR5usmQ4QP_ocNfACwzCR1lQLIapck9SWk

{

    "name": "Netscape",
    "url": "https://www.microsoft.com",
    "pointOfContact": {
        "name": "Satya Nadella",
        "email": "Satya@microsoft.com",
        "phone": "999-999-9999"
    }
}


###
GET https://localhost:9000/vendors/108a7f68-27eb-4fd5-9738-a8bced68e964


REST

GET /policies/{id}

{
    "id": "jeff-policy-number",
    "_links": {
        "self": {
            "href": "/policies/jeff-policy-number"
        },
        "standing": {
            "href": "/policies/jeff-policy-number/standing"
        },
        "vehicles": {
            "href": "http://api2.other-server.com/policies/jeff-policy-number/vehicles"
        
        }, 
        "drivers": {
            "href": "/policies/jeff-policy-number/drivers"
        }
    }
    
}

How can I design this so I don't break clients?

- "Quiet Quitting" - only work to the job description 


