GET https://localhost:9000/


###

POST https://localhost:9000/vendors
Content-Type: application/json 

{
    "name": "Microsoft",
    "url": "https://www.microsoft.com",
    "pointOfContact": {
        "name": "Satya Nadella",
        "email": "Satya@microsoft.com",
        "phone": "999-999-9999"
    }
}


###
GET https://localhost:9000/vendors/2d31bc2e-2a67-4b0f-8130-759b1c6b3f23